sudo: required
language: go
go:
    - "1.12"

services:
  - docker

install: true

script: 
  - echo "Run your tests here"

before_install:
  # Download and install Kind and kubectl
  - GO111MODULE=on go get sigs.k8s.io/kind
  - kind build node-image --type apt
  - kind create cluster --config kind-config.yaml --image kindest/node:latest
  - export KUBECONFIG="$(kind get kubeconfig-path --name="kind")"
  - curl -LO https://storage.googleapis.com/kubernetes-release/release/$(curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt)/bin/linux/amd64/kubectl
  - chmod +x ./kubectl
  - ./kubectl wait -n kube-system --for=condition=Ready -l k8s-app=kube-dns pods
  - ./kubectl get nodes -o wide
  - ./kubectl get pods --all-namespaces -o wide
  - ./kubectl get services --all-namespaces -o wide
  - curl http://google.com
  - docker exec kind-control-plane iptables-save
  - ./kubectl apply -f https://k8s.io/examples/admin/dns/busybox.yaml
  - ./kubectl wait --for=condition=Ready pod busybox
  - ./kubectl exec -ti busybox -- cat /etc/resolv.conf
  - ./kubectl exec -ti busybox -- nslookup kubernetes.default
  - ./kubectl exec -ti busybox -- nslookup www.google.com || true
  - ./kubectl exec -ti busybox -- nslookup www.google.com 8.8.8.8
  - ./kubectl exec -ti busybox -- ip a
  - for p in $(./kubectl get pods --namespace=kube-system -l k8s-app=kube-dns -o name); do ./kubectl logs --namespace=kube-system $p; done

